### ISSUE TITLE
User buffer/daemon buffer corruption on 2.18.6

### ISSUE THREAD

**Issue by andreirusu96** [GENIVI/dlt-daemon#305]
Hello!

I'm currently working on upgrading to version 2.18.6 of DLT Daemon on our QNX platform and I encountered **2 issues**. Both seem related to a user/daemon buffer corruption and they also reproduce on a Linux build of dlt-daemon (tested on Ubuntu 16.04)

The issues can be easily reproduced by using included test applications. I will show exact examples for each case below.

## 1. Commit [gtest_dlt_common: fix seg fault when using memcpy()](https://github.com/GENIVI/dlt-daemon/commit/929a02f18556b9f1109c84d784a56de1e36a6e41)

This commit causes a DLT User buffer corruption issue resulting in lost messages and corruption. The following repeated error can be seen:

`[  300.160637]~DLT~3027036~ERROR    ~dlt_buffer_get: Buffer: Header head check failed`
`[  300.160731]~DLT~3027036~WARNING  ~dlt_buffer_reset: Buffer: Buffer reset triggered. Size: 49988, Start address: 30D882A04C`

To reproduce, we simply use the included _dlt-test-stress-user_ application with a 0 delay between messages:

`dlt-test-stress-user -d 0 | grep Buffer`

*The output was redirected because it slows down execution of the DLT User code which, I suppose, causes the DLT User buffer of the app not to fill up as fast.

*At the moment I cannot reproduce the issue on Linux because the DLT Daemon is much faster at processing messages, but on QNX, as soon as the User buffer starts to fill up, we encounter the issue. 

**Reverting this commit completely solves this specific issue.** I understand why the check was added in the commit, however, is it possible that the read/write pointer increment should have also been moved inside the if branch? [Write increment](https://github.com/GENIVI/dlt-daemon/commit/929a02f18556b9f1109c84d784a56de1e36a6e41#diff-e59843eccec1d5123950473e013e1fe4057139368852b78b8fb46606a52c5ebcR2400) / [Read increment](https://github.com/GENIVI/dlt-daemon/commit/929a02f18556b9f1109c84d784a56de1e36a6e41#diff-e59843eccec1d5123950473e013e1fe4057139368852b78b8fb46606a52c5ebcL2423) 

## 2. Buffer corruption caused by unknown commit between 2.18.5 and 2.18.6

**This issue is not present in any of the previous versions of DLT 2.18** (I've tested each one of them starting with 2.18.0 up to 2.18.5).

The second issue can be easily reproduced on both QNX and Linux by using the included _dlt-example-user_ test application **together with a longer string message** (for example, one around 400 chars) and a 0 delay between messages: 

`dlt-example-user -n 1000000 -l 3 -d 0 "This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message" > /dev/null`

**The issue does not reproduce when using smaller messages**. For example, the following command does not lead to the buffers being corrupted:

`dlt-example-user -n 1000000 -l 3 -d 0 "This is my first log message" > /dev/null`

*In both cases, the output was redirected because it slows down execution of the DLT User code which, I suppose, causes the DLT User buffer of the app not to fill up as fast.

Of course, the application will report that the user buffer is full:

`[345972.692495]~DLT~31484~WARNING  ~Buffer full! Messages will be discarded.`

In this case, the following can be seen on an DLT Viewer connected to the daemon (these are 3 separate message payloads):

`12889 This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This DUH`
`12891 This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This DUH`
`12893 This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This is my first log message This DUH
`

As can bee seen, some logs are missing (which is expected since the User buffer is full) but it is clear that messages are wrongly cut.

Let me know if there's any other information that I can provide! Thanks!

**Comment by cogle** [comment]
@andreirusu96 
For issue number 1 out of curiosity did you try moving the write/read increment into the if statement and observe if that issue was resolved in doing so. From the code I think you are correct as that could erroneously increment the index.

I was also wondering if you had any possible lead on the second issue you mentioned. 

Note: I am not a dev for this library but was curious into looking into it.

Thanks.

**Comment by thanhbnq** [comment]
Hello all,

Thanks for your report and very detailed information!
Currently, we are a little bit busy but we will try to give our feedback as soon as possible!

Thank you for your understanding and patience!
Thanh

**Comment by tdinhcong** [comment]
Hi @cogle and @andreirusu96, 

Sorry for the late response from us and thanks for your detail report !
In both cases you report, dlt user try to send abundant log to dlt-daemon without any clients connected to daemon this time. In a short time, daemon buffer and user buffer will be fulfilled (no client connected to get log msg, so it will be stored in buffer). This time, dlt-client will increase the size of buffer and store the next message.

I find out that when handling the case of buffer full in dlt-user, I tried explicitly cast some variables to wrong type, which leads to corruption the message in the case buffer full.

### For case 2:
+ I suggest the patch below to correct the casting. From my side, the patch can fix the **case 2**. Can you apply this patch, verify it in your own project and feedback to us?

+ In dlt_user.c, line [4764](https://github.com/GENIVI/dlt-daemon/blob/e969bed805f7dba9d2fa35c56a7ace28efb67e4e/src/lib/dlt_user.c#L4764):
```
@@ -4762,9 +4761,9 @@ DltReturnValue dlt_user_log_out_error_handling(void *ptr1, size_t len1, void *pt
     DLT_SEM_LOCK();

     if (dlt_buffer_push3(&(dlt_user.startup_buffer),
-                         ptr1, (unsigned char)len1,
-                         ptr2, (unsigned char)len2,
-                         ptr3, (unsigned char)len3) == DLT_RETURN_ERROR) {
+                         ptr1, (unsigned int) len1,
+                         ptr2, (unsigned int) len2,
+                         ptr3, (unsigned int) len3) == DLT_RETURN_ERROR) {
          if (dlt_user.overflow_counter == 0)
             dlt_log(LOG_WARNING, "Buffer full! Messages will be discarded.\n");
```

### For case 1: 
+ For me, with or without my old [change](https://github.com/GENIVI/dlt-daemon/commit/929a02f18556b9f1109c84d784a56de1e36a6e41) seems do not lead to the error in checking header. The issue seems related to break the header of message, so it can be the same error with case 1. I have not checked the issue in QNX environment yet, so it is very please for me if you will use the patch above and check again this issue. 

Thank you all for your contribution and feel free to have more discussions.

**Comment by cogle** [comment]
Hi @tdinhcong,
I will test out your patch as soon as I have time.
Regarding issue 1, I am wondering is this code exhibiting correct behavior [code in question](https://github.com/GENIVI/dlt-daemon/commit/929a02f18556b9f1109c84d784a56de1e36a6e41#diff-e59843eccec1d5123950473e013e1fe4057139368852b78b8fb46606a52c5ebcR2400).
In this case the increment to write happens even if there is no data written, same for the read operation. This is what @andreirusu96 was pointing out and would appreciate any clarification as to why you might increment even if the write never occurs.
Thanks!

**Comment by tdinhcong** [comment]
Hi @cogle, 

Thank for your pointing out. I think it is reasonable that with my change, the index of write or read position can be updated incorrectly even not doing copy any data to dlt buffer. As you said, revert my change can fix the issue in case 1, right?

After that, can you have confirmed the results for case 1 and case 2 (with my patch) are fixed or not? 

Thank you.

**Comment by andreirusu96** [comment]
Hello @cogle and @tdinhcong ! 

Related to your question, @cogle : yes, I did test Issue 2 with the suspected commit from Issue 1 removed. Otherwise, the buffer would never get full to reach Issue 2, since a buffer reset was being triggered by Issue 1 before a resize would happen (_~dlt_buffer_reset: Buffer: Buffer reset triggered._ ) - see above patch!

Thank you for the patch, @tdinhcong! Unfortunately, I didn't manage to test the patch on QNX, but I did test it on Linux and **it solved Issue 2** (as explained in the original post, I cannot reproduce Issue 1 on Linux).

I will try to test the patch on QNX in the following days and return with the results.

Thanks again!

**Comment by andreirusu96** [comment]
Hello again!

I've done the tests on QNX and, as expected, **the patch for case 2 works well**. However, the first issue is still present, causing corruption, so, in order to have fully working DLT on our platform, **we also need to also revert the specified commit in case 1**.

I added a simple print right where the suspected change is: 

```
diff --git a/src/shared/dlt_common.c b/src/shared/dlt_common.c
index 7b95ab3..84082ef 100644
--- a/src/shared/dlt_common.c
+++ b/src/shared/dlt_common.c
@@ -2421,6 +2421,9 @@ void dlt_buffer_write_block(DltBuffer *buf, int *write, const unsigned char *dat
                     memcpy(buf->mem + *write, data, buf->size - (unsigned int) (*write));
                     memcpy(buf->mem, data + buf->size - *write, size - buf->size + (unsigned int) (*write));
                 }
+                else
+                    dlt_vlog(LOG_WARNING, "%s: Buffer: Incrementing write pointer without memcopy: Buff->size: %i (*write): %i \n",__func__, buf->size, (unsigned int) (*write));
+
                 *write += (int) (size - buf->size);
             }
 	}
```

At runtime, the added print is shown, immediately followed by visible Log corruption inside DLT Viewer:

`[   88.417116]~DLT~2039836~WARNING  ~dlt_buffer_write_block: Buffer: Incrementing write pointer without memcopy: Buff->size: 49988 (*write): 49988`

**Comment by tdinhcong** [comment]
Hi @andreirusu96,

Thank you for your confirm. We are going to upstream DLT to new version in the next few weeks. So for the first issues, can you verify this issue again when new version is available?

**Comment by tdinhcong** [comment]
Hi @andreirusu96, 
Can you verify with our latest version (2.18.7) again for this issue?

**Comment by andreirusu96** [comment]
Hello, @tdinhcong !

I did a test on Linux and, unfortunately, it seems that you omitted to also commit the patch that you provided for `dlt_user_log_out_error_handling` ( `dlt_user.c` ) in your comment above. This means that Case 2 of my initial post is still not solved on the `master` branch of DLT Daemon (v2.18.7). Just for confirmation, the provided patch solved Case 2.

I will try to perform a test on our platform (using QNX) for Case 1 in the following days and return with the results.

Thanks a lot for your efforts!

**Comment by tdinhcong** [comment]
Hi @andreirusu96, 

Just inform that my [sugesstion patch](https://github.com/GENIVI/dlt-daemon/pull/324) have been merged to ```master``` branch.
Please let us know when you have test results for case 1. 

Thanks so much.

**Comment by andreirusu96** [comment]
Hello, @tdinhcong ! 

I've done the tests on QNX for both cases and I can no longer see any issue related to the first post.

As such, from my point of view, the Issue(s) are now solved.

Thank you very much for you efforts!
